version: '3'
services:
  php-5.6:
    container_name: php-5.6
    image: ashenud/multiple-php-versions:1st-bulid-5.6
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "/var/www/5.6:/var/www"
    networks:
      backend-link:
      database-link:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

  php-7.4:
    container_name: php-7.4
    image: ashenud/multiple-php-versions:1st-bulid-7.4
    restart: always
    ports:
      - "9090:80"
    volumes:
      - "/var/www/7.4:/var/www"
    networks:
      backend-link:
      database-link:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::11

  database:
    container_name: mysql-8.0
    image: mysql/mysql-server
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "${DOCKER_DATA_LOCATION}/mysql/databases:/var/lib/mysql"
      - "${DOCKER_DATA_LOCATION}/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      database-link:
        ipv4_address: 172.16.238.12
        ipv6_address: 2001:3984:3989::12

networks:
  backend-link:    
    name: backend-link
  database-link:
    name: database-link
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"